export const currencyCodes = [
  { value: "AED", label: "Egyesült Arab Emírségek dirham" },
  { value: "AFN", label: "Afgán afgani" },
  { value: "ALL", label: "Albán lek" },
  { value: "AMD", label: "Örmény dram" },
  { value: "ANG", label: "Holland antillai forint" },
  { value: "AOA", label: "Angolai kwanza" },
  { value: "ARS", label: "Argentin peso" },
  { value: "AUD", label: "Ausztrál dollár" },
  { value: "AWG", label: "Arubai forint" },
  { value: "AZN", label: "Azerbajdzsáni manat" },
  { value: "BAM", label: "Bosznia-hercegovinai konvertibilis márka" },
  { value: "BBD", label: "Barbadosi dollár" },
  { value: "BDT", label: "Bangladesi taka" },
  { value: "BGN", label: "Bolgár leva" },
  { value: "BHD", label: "Bahreini dinár" },
  { value: "BIF", label: "Burundi frank" },
  { value: "BMD", label: "Bermudai dollár" },
  { value: "BND", label: "Brunei dollár" },
  { value: "BOB", label: "Bolíviai boliviano" },
  { value: "BOV", label: "Bolíviai MVDOL" },
  { value: "BRL", label: "Brazil real" },
  { value: "BSD", label: "Bahamai dollár" },
  { value: "BTN", label: "Bhutáni ngultrum" },
  { value: "BWP", label: "Botswanai pula" },
  { value: "BYN", label: "Fehérorosz rubel" },
  { value: "BZD", label: "Belize-i dollár" },
  { value: "CAD", label: "Kanadai dollár" },
  { value: "CDF", label: "Kongói frank" },
  { value: "CHE", label: "WIR euró" },
  { value: "CHF", label: "Svájci frank" },
  { value: "CHW", label: "WIR frank" },
  { value: "CLF", label: "Chilei fomento egység" },
  { value: "CLP", label: "Chilei peso" },
  { value: "CNY", label: "Kínai jüan" },
  { value: "COP", label: "Kolumbiai peso" },
  { value: "COU", label: "Kolumbiai valódi érték egység" },
  { value: "CRC", label: "Costa Rica-i colón" },
  { value: "CUC", label: "Kubai konvertibilis peso" },
  { value: "CUP", label: "Kubai peso" },
  { value: "CVE", label: "Zöld-foki escudo" },
  { value: "CZK", label: "Cseh korona" },
  { value: "DJF", label: "Dzsibuti frank" },
  { value: "DKK", label: "Dán korona" },
  { value: "DOP", label: "Dominikai peso" },
  { value: "DZD", label: "Algériai dinár" },
  { value: "EGP", label: "Egyiptomi font" },
  { value: "ERN", label: "Eritreai nakfa" },
  { value: "ETB", label: "Etiópiai birr" },
  { value: "EUR", label: "Euró" },
  { value: "FJD", label: "Fidzsi dollár" },
  { value: "FKP", label: "Falkland-szigeteki font" },
  { value: "GBP", label: "Angol font" },
  { value: "GEL", label: "Grúz lari" },
  { value: "GHS", label: "Ghanai cedi" },
  { value: "GIP", label: "Gibraltári font" },
  { value: "GMD", label: "Gambiai dalasi" },
  { value: "GNF", label: "Guineai frank" },
  { value: "GTQ", label: "Guatemalai quetzal" },
  { value: "GYD", label: "Guyanai dollár" },
  { value: "HKD", label: "Hongkongi dollár" },
  { value: "HNL", label: "Hondurasi lempira" },
  { value: "HTG", label: "Haiti gourde" },
  { value: "HUF", label: "Magyar forint" },
  { value: "IDR", label: "Indonéz rúpia" },
  { value: "ILS", label: "Izraeli új sékel" },
  { value: "INR", label: "Indiai rúpia" },
  { value: "IQD", label: "Iraki dinár" },
  { value: "IRR", label: "Iráni rial" },
  { value: "ISK", label: "Izlandi korona" },
  { value: "JMD", label: "Jamaicai dollár" },
  { value: "JOD", label: "Jordániai dinár" },
  { value: "JPY", label: "Japán jen" },
  { value: "KES", label: "Kenya shilling" },
  { value: "KGS", label: "Kirgiz szom" },
  { value: "KMF", label: "Comore-i frank" },
  { value: "KPW", label: "Észak-koreai won" },
  { value: "KRW", label: "Dél-koreai won" },
  { value: "KWD", label: "Kuvaiti dinár" },
  { value: "KYD", label: "Kajmán-szigeteki dollár" },
  { value: "KZT", label: "Kazah tenge" },
  { value: "LAK", label: "Laoszi kip" },
  { value: "LBP", label: "Libanoni font" },
  { value: "LKR", label: "Srí Lanka-i rúpia" },
  { value: "LRD", label: "Libériai dollár" },
  { value: "LSL", label: "Lesothói loti" },
  { value: "LYD", label: "Líbiai dinár" },
  { value: "MAD", label: "Marokkói dirham" },
  { value: "MDL", label: "Moldovai lej" },
  { value: "MGA", label: "Madagaszkári ariary" },
  { value: "MKD", label: "Észak-macedón dénár" },
  { value: "MMK", label: "Mianmari kyat" },
  { value: "MNT", label: "Mongol tugrik" },
  { value: "MOP", label: "Makaói pataca" },
  { value: "MRU", label: "Mauritániai ouguiya" },
  { value: "MUR", label: "Mauritiusi rúpia" },
  { value: "MVR", label: "Maldív rufiyaa" },
  { value: "MWK", label: "Malawi kwacha" },
  { value: "MXN", label: "Mexikói peso" },
  { value: "MXV", label: "Mexikói UDI" },
  { value: "MYR", label: "Malajziai ringgit" },
  { value: "MZN", label: "Mozambiki metical" },
  { value: "NAD", label: "Namíbiai dollár" },
  { value: "NGN", label: "Nigériai naira" },
  { value: "NIO", label: "Nicaraguai córdoba" },
  { value: "NOK", label: "Norvég korona" },
  { value: "NPR", label: "Nepáli rúpia" },
  { value: "NZD", label: "Új-zélandi dollár" },
  { value: "OMR", label: "Ománi rial" },
  { value: "PAB", label: "Panamai balboa" },
  { value: "PEN", label: "Perui sol" },
  { value: "PGK", label: "Pápua új-guineai kina" },
  { value: "PHP", label: "Fülöp-szigeteki peso" },
  { value: "PKR", label: "Pakisztáni rúpia" },
  { value: "PLN", label: "Lengyel zloty" },
  { value: "PYG", label: "Paraguayi guaraní" },
  { value: "QAR", label: "Katari rial" },
  { value: "RON", label: "Román lej" },
  { value: "RSD", label: "Szerb dinár" },
  { value: "RUB", label: "Orosz rubel" },
  { value: "RWF", label: "Ruandai frank" },
  { value: "SAR", label: "Szaúdi riyal" },
  { value: "SBD", label: "Salamon-szigeteki dollár" },
  { value: "SCR", label: "Seychelle-szigeteki rúpia" },
  { value: "SDG", label: "Szudáni font" },
  { value: "SEK", label: "Svéd korona" },
  { value: "SGD", label: "Szingapúri dollár" },
  { value: "SHP", label: "Szent Ilona-i font" },
  { value: "SLE", label: "Sierra Leone-i leone" },
  { value: "SOS", label: "Szomáli shilling" },
  { value: "SRD", label: "Suriname-i dollár" },
  { value: "SSP", label: "Dél-szudáni font" },
  { value: "STN", label: "São Tomé és Príncipe dobra" },
  { value: "SVC", label: "Salvadori colón" },
  { value: "SYP", label: "Szíriai font" },
  { value: "SZL", label: "Szváziföldi lilangeni" },
  { value: "THB", label: "Thai baht" },
  { value: "TJS", label: "Tádzsik szomoni" },
  { value: "TMT", label: "Türkmen manat" },
  { value: "TND", label: "Tunéziai dinár" },
  { value: "TOP", label: "Tongai paʻanga" },
  { value: "TRY", label: "Török líra" },
  { value: "TTD", label: "Trinidad és Tobago-i dollár" },
  { value: "TWD", label: "Tajvani új dollár" },
  { value: "TZS", label: "Tanzániai shilling" },
  { value: "UAH", label: "Ukrán hrivnya" },
  { value: "UGX", label: "Ugandai shilling" },
  { value: "USD", label: "Amerikai dollár" },
  { value: "USN", label: "Amerikai dollár (következő napi)" },
  { value: "UYI", label: "Uruguayi peso en unidades indexadas" },
  { value: "UYU", label: "Uruguayi peso" },
  { value: "UYW", label: "Uruguayi egység munkabérindexáláshoz" },
  { value: "UZS", label: "Üzbegisztáni szom" },
  { value: "VED", label: "Venezuelai gazdasági valuta" },
  { value: "VES", label: "Venezuelai bolívar" },
  { value: "VND", label: "Vietnámi dong" },
  { value: "VUV", label: "Vanuatui vatu" },
  { value: "WST", label: "Szamoai tala" },
  { value: "XAF", label: "Közép-afrikai CFA frank" },
  { value: "XAG", label: "Ezüst (nem valuta)" },
  { value: "XAU", label: "Arany (nem valuta)" },
  { value: "XBA", label: "Európai kompozit egység" },
  { value: "XBB", label: "Európai monetáris egység" },
  { value: "XBC", label: "Európai számviteli egység (XBC)" },
  { value: "XBD", label: "Európai számviteli egység (XBD)" },
  { value: "XCD", label: "Kelet-karibi dollár" },
  { value: "XDR", label: "Különleges lehívási jogok (IMF)" },
  { value: "XOF", label: "Nyugat-afrikai CFA frank" },
  { value: "XPD", label: "Palládium (nem valuta)" },
  { value: "XPF", label: "CFP frank" },
  { value: "XPT", label: "Platina (nem valuta)" },
  { value: "XSU", label: "SUCRE" },
  { value: "XTS", label: "Tesztelési célú valuta kód" },
  { value: "XUA", label: "ADB számviteli egység" },
  { value: "XXX", label: "Ismeretlen vagy érvénytelen valuta" },
  { value: "YER", label: "Jemeni rial" },
  { value: "ZAR", label: "Dél-afrikai rand" },
  { value: "ZMW", label: "Zambiai kwacha" },
  { value: "ZWL", label: "Zimbabwei dollár" }
] as const

export const countryCodes = [
  { value: "AF", label: "Afganisztán" },
  { value: "AL", label: "Albánia" },
  { value: "DZ", label: "Algéria" },
  { value: "AS", label: "Amerikai Szamoa" },
  { value: "AD", label: "Andorra" },
  { value: "AO", label: "Angola" },
  { value: "AI", label: "Anguilla" },
  { value: "AQ", label: "Antarktisz" },
  { value: "AG", label: "Antigua és Barbuda" },
  { value: "AR", label: "Argentína" },
  { value: "AM", label: "Örményország" },
  { value: "AW", label: "Aruba" },
  { value: "AU", label: "Ausztrália" },
  { value: "AT", label: "Ausztria" },
  { value: "AZ", label: "Azerbajdzsán" },
  { value: "BS", label: "Bahama-szigetek" },
  { value: "BH", label: "Bahrein" },
  { value: "BD", label: "Banglades" },
  { value: "BB", label: "Barbados" },
  { value: "BY", label: "Fehéroroszország" },
  { value: "BE", label: "Belgium" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Benin" },
  { value: "BM", label: "Bermuda" },
  { value: "BT", label: "Bhután" },
  { value: "BO", label: "Bolívia" },
  { value: "BQ", label: "Bonaire, Sint Eustatius és Saba" },
  { value: "BA", label: "Bosznia-Hercegovina" },
  { value: "BW", label: "Botswana" },
  { value: "BR", label: "Brazília" },
  { value: "IO", label: "Brit Indiai-óceáni Terület" },
  { value: "BN", label: "Brunei" },
  { value: "BG", label: "Bulgária" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "KH", label: "Kambodzsa" },
  { value: "CM", label: "Kamerun" },
  { value: "CA", label: "Kanada" },
  { value: "CV", label: "Zöld-foki Köztársaság" },
  { value: "CF", label: "Közép-afrikai Köztársaság" },
  { value: "TD", label: "Csád" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "Kína" },
  { value: "CO", label: "Kolumbia" },
  { value: "KM", label: "Comore-szigetek" },
  { value: "CG", label: "Kongó (Brazzaville)" },
  { value: "CD", label: "Kongó (Kinshasa)" },
  { value: "CR", label: "Costa Rica" },
  { value: "CI", label: "Elefántcsontpart" },
  { value: "HR", label: "Horvátország" },
  { value: "CU", label: "Kuba" },
  { value: "CW", label: "Curaçao" },
  { value: "CY", label: "Ciprus" },
  { value: "CZ", label: "Csehország" },
  { value: "DK", label: "Dánia" },
  { value: "DJ", label: "Dzsibuti" },
  { value: "DM", label: "Dominika" },
  { value: "DO", label: "Dominikai Köztársaság" },
  { value: "EC", label: "Ecuador" },
  { value: "EG", label: "Egyiptom" },
  { value: "SV", label: "Salvador" },
  { value: "GQ", label: "Egyenlítői-Guinea" },
  { value: "ER", label: "Eritrea" },
  { value: "EE", label: "Észtország" },
  { value: "ET", label: "Etiópia" },
  { value: "FJ", label: "Fidzsi-szigetek" },
  { value: "FI", label: "Finnország" },
  { value: "FR", label: "Franciaország" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia" },
  { value: "GE", label: "Grúzia" },
  { value: "DE", label: "Németország" },
  { value: "GH", label: "Ghána" },
  { value: "GR", label: "Görögország" },
  { value: "GL", label: "Grönland" },
  { value: "GD", label: "Grenada" },
  { value: "GU", label: "Guam" },
  { value: "GT", label: "Guatemala" },
  { value: "GN", label: "Guinea" },
  { value: "GW", label: "Bissau-Guinea" },
  { value: "GY", label: "Guyana" },
  { value: "HT", label: "Haiti" },
  { value: "HN", label: "Honduras" },
  { value: "HK", label: "Hongkong" },
  { value: "HU", label: "Magyarország" },
  { value: "IS", label: "Izland" },
  { value: "IN", label: "India" },
  { value: "ID", label: "Indonézia" },
  { value: "IR", label: "Irán" },
  { value: "IQ", label: "Irak" },
  { value: "IE", label: "Írország" },
  { value: "IL", label: "Izrael" },
  { value: "IT", label: "Olaszország" },
  { value: "JM", label: "Jamaica" },
  { value: "JP", label: "Japán" },
  { value: "JO", label: "Jordánia" },
  { value: "KZ", label: "Kazahsztán" },
  { value: "KE", label: "Kenya" },
  { value: "KI", label: "Kiribati" },
  { value: "KW", label: "Kuvait" },
  { value: "KG", label: "Kirgizisztán" },
  { value: "LA", label: "Laosz" },
  { value: "LV", label: "Lettország" },
  { value: "LB", label: "Libanon" },
  { value: "LS", label: "Lesotho" },
  { value: "LR", label: "Libéria" },
  { value: "LY", label: "Líbia" },
  { value: "LI", label: "Liechtenstein" },
  { value: "LT", label: "Litvánia" },
  { value: "LU", label: "Luxemburg" },
  { value: "MO", label: "Makaó" },
  { value: "MG", label: "Madagaszkár" },
  { value: "MW", label: "Malawi" },
  { value: "MY", label: "Malajzia" },
  { value: "MV", label: "Maldív-szigetek" },
  { value: "ML", label: "Mali" },
  { value: "MT", label: "Málta" },
  { value: "MH", label: "Marshall-szigetek" },
  { value: "MQ", label: "Martinique" },
  { value: "MR", label: "Mauritánia" },
  { value: "MU", label: "Mauritius" },
  { value: "YT", label: "Mayotte" },
  { value: "MX", label: "Mexikó" },
  { value: "FM", label: "Mikronézia" },
  { value: "MD", label: "Moldova" },
  { value: "MC", label: "Monaco" },
  { value: "MN", label: "Mongólia" },
  { value: "ME", label: "Montenegró" },
  { value: "MS", label: "Montserrat" },
  { value: "MA", label: "Marokkó" },
  { value: "MZ", label: "Mozambik" },
  { value: "MM", label: "Mianmar" },
  { value: "NA", label: "Namíbia" },
  { value: "NR", label: "Nauru" },
  { value: "NP", label: "Nepál" },
  { value: "NL", label: "Hollandia" },
  { value: "NZ", label: "Új-Zéland" },
  { value: "NI", label: "Nicaragua" },
  { value: "NE", label: "Niger" },
  { value: "NG", label: "Nigéria" },
  { value: "KP", label: "Észak-Korea" },
  { value: "MK", label: "Észak-Macedónia" },
  { value: "NO", label: "Norvégia" },
  { value: "OM", label: "Omán" },
  { value: "PK", label: "Pakisztán" },
  { value: "PW", label: "Palau" },
  { value: "PS", label: "Palesztina" },
  { value: "PA", label: "Panama" },
  { value: "PG", label: "Pápua Új-Guinea" },
  { value: "PY", label: "Paraguay" },
  { value: "PE", label: "Peru" },
  { value: "PH", label: "Fülöp-szigetek" },
  { value: "PL", label: "Lengyelország" },
  { value: "PT", label: "Portugália" },
  { value: "PR", label: "Puerto Rico" },
  { value: "QA", label: "Katar" },
  { value: "RO", label: "Románia" },
  { value: "RU", label: "Oroszország" },
  { value: "RW", label: "Ruanda" },
  { value: "WS", label: "Szamoa" },
  { value: "SM", label: "San Marino" },
  { value: "ST", label: "São Tomé és Príncipe" },
  { value: "SA", label: "Szaúd-Arábia" },
  { value: "SN", label: "Szenegál" },
  { value: "RS", label: "Szerbia" },
  { value: "SC", label: "Seychelle-szigetek" },
  { value: "SL", label: "Sierra Leone" },
  { value: "SG", label: "Szingapúr" },
  { value: "SK", label: "Szlovákia" },
  { value: "SI", label: "Szlovénia" },
  { value: "SB", label: "Salamon-szigetek" },
  { value: "SO", label: "Szomália" },
  { value: "ZA", label: "Dél-Afrika" },
  { value: "KR", label: "Dél-Korea" },
  { value: "SS", label: "Dél-Szudán" },
  { value: "ES", label: "Spanyolország" },
  { value: "LK", label: "Srí Lanka" },
  { value: "SD", label: "Szudán" },
  { value: "SR", label: "Suriname" },
  { value: "SE", label: "Svédország" },
  { value: "CH", label: "Svájc" },
  { value: "SY", label: "Szíria" },
  { value: "TW", label: "Tajvan" },
  { value: "TJ", label: "Tádzsikisztán" },
  { value: "TZ", label: "Tanzánia" },
  { value: "TH", label: "Thaiföld" },
  { value: "TL", label: "Kelet-Timor" },
  { value: "TG", label: "Togo" },
  { value: "TO", label: "Tonga" },
  { value: "TT", label: "Trinidad és Tobago" },
  { value: "TN", label: "Tunézia" },
  { value: "TR", label: "Törökország" },
  { value: "TM", label: "Türkmenisztán" },
  { value: "TV", label: "Tuvalu" },
  { value: "UG", label: "Uganda" },
  { value: "UA", label: "Ukrajna" },
  { value: "AE", label: "Egyesült Arab Emírségek" },
  { value: "GB", label: "Egyesült Királyság" },
  { value: "US", label: "Egyesült Államok" },
  { value: "UY", label: "Uruguay" },
  { value: "UZ", label: "Üzbegisztán" },
  { value: "VU", label: "Vanuatu" },
  { value: "VA", label: "Vatikán" },
  { value: "VE", label: "Venezuela" },
  { value: "VN", label: "Vietnám" },
  { value: "YE", label: "Jemen" },
  { value: "ZM", label: "Zambia" },
  { value: "ZW", label: "Zimbabwe" }
] as const


export const paymentMethods = [
  { value: "TRANSFER", label: "Átutalás" },
  { value: "CASH", label: "Készpénz" },
  { value: "CARD", label: "Bankkártya" },
  { value: "VOUCHER", label: "Utalvány" },
  { value: "OTHER", label: "Egyéb" },
] as const



